export { canonicalizeUrl } from "./canonical-url.js";
export { crawl, type FetchResult, type CrawlDeps } from "./crawl.js";
export { fetchSitemapUrls } from "./sitemap.js";
export { loadRobots, type RobotsInfo } from "./robots.js";
export * from "./mapper.js";
export { issueFingerprint, normalizeHtml } from "./fingerprint.js";
export { scanUrl, closeBrowser, getBrowser, type ScanResult } from "./scanner.js";
export { makeFetchPage } from "./playwright-adapter.js";
export { runScan } from "./run-scan.js";
export * from "./wcag-catalog.js";
export * from "./sc-mapping.js";
export * from "./scoring.js";
export * from "./criterion-states.js";
export * from "./verdict.js";
export * from "./scan-diff.js";
export { buildScanAnalysis, type ScanAnalysis } from "./scan-analysis.js";
export type { CrawledPage } from "./crawl.js";
export { executeLogin, mapRecipe, type StorageState, type LoginRecipeInput, type ResolveSecret } from "./recipe-runner.js";
export * from "./manual-review.js";
