// Italian titles for WCAG 2.1 A/AA success criteria (the 50 scanned by AccessScan).
const WCAG_TITLES: Record<string, string> = {
  "1.1.1": "Contenuti non testuali",
  "1.2.1": "Solo audio e solo video (preregistrato)",
  "1.2.2": "Sottotitoli (preregistrati)",
  "1.2.3": "Audiodescrizione o supporto multimediale alternativo (preregistrato)",
  "1.2.4": "Sottotitoli (in tempo reale)",
  "1.2.5": "Audiodescrizione (preregistrata)",
  "1.3.1": "Informazioni e correlazioni",
  "1.3.2": "Sequenza significativa",
  "1.3.3": "Caratteristiche sensoriali",
  "1.3.4": "Orientamento",
  "1.3.5": "Identificare lo scopo dell'input",
  "1.4.1": "Uso del colore",
  "1.4.2": "Controllo del sonoro",
  "1.4.3": "Contrasto (minimo)",
  "1.4.4": "Ridimensionamento del testo",
  "1.4.5": "Immagini di testo",
  "1.4.10": "Ridistribuzione (Reflow)",
  "1.4.11": "Contrasto del contenuto non testuale",
  "1.4.12": "Spaziatura del testo",
  "1.4.13": "Contenuto al passaggio del mouse o del focus",
  "2.1.1": "Tastiera",
  "2.1.2": "Nessun impedimento all'uso della tastiera",
  "2.1.4": "Scorciatoie da tastiera con un solo carattere",
  "2.2.1": "Regolazione dei tempi",
  "2.2.2": "Pausa, stop, nascondi",
  "2.3.1": "Tre lampeggiamenti o sotto la soglia",
  "2.4.1": "Salto di blocchi",
  "2.4.2": "Titolo della pagina",
  "2.4.3": "Ordine del focus",
  "2.4.4": "Scopo del collegamento (nel contesto)",
  "2.4.5": "Differenti modalità",
  "2.4.6": "Intestazioni ed etichette",
  "2.4.7": "Focus visibile",
  "2.5.1": "Gesti del puntatore",
  "2.5.2": "Annullamento delle azioni del puntatore",
  "2.5.3": "Etichetta nel nome",
  "2.5.4": "Attivazione tramite movimento",
  "3.1.1": "Lingua della pagina",
  "3.1.2": "Lingua di una parte",
  "3.2.1": "Al focus",
  "3.2.2": "All'input",
  "3.2.3": "Navigazione coerente",
  "3.2.4": "Identificazione coerente",
  "3.3.1": "Identificazione degli errori",
  "3.3.2": "Etichette o istruzioni",
  "3.3.3": "Suggerimento per gli errori",
  "3.3.4": "Prevenzione degli errori (legali, finanziari, dati)",
  "4.1.1": "Elaborazione (Parsing)",
  "4.1.2": "Nome, ruolo, valore",
  "4.1.3": "Messaggi di stato",
};

/** Italian title for a WCAG SC code, or empty string if unknown. */
export function wcagTitle(sc: string): string {
  return WCAG_TITLES[sc] ?? "";
}
